# NumPy Quickstart
For more detail please refer to https://numpy.org/doc/stable/user/quickstart.html

### Array Creation

In [ ]:
import numpy as np

# Creating a 2D array
a = np.arange(15).reshape(3, 5) # Rows: 3, Columns: 5, with range 0-14
print(a)
print("=" * 100)
# NumPy `arange` is similar to Python's built-in `range`, but returns an array instead of a list

# Dimension of the array
print(f"Dimension of the array: {a.shape}, total number of elements: {a.size}, number of axis: {a.ndim}")

# Checking the type of the array
print(f"Type of the array: {a.dtype}")

# Itemsize of each element in bytes
print(f"Itemsize of each element: {a.itemsize} bytes")


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Dimension of the array: (3, 5), total number of elements: 15, number of axis: 2
Type of the array: int64
Itemsize of each element: 8 bytes


There are 4 ways for you to create an array: 1. `np.arange(x).rehsape(y, z)`; 2. using `np.array([add your own list of numbers here])`; 3. using placeholders; 4. using `np.linspace()`

In [ ]:
# For method 1, refer to the code above
# For method 2, you could also specify the data type, e.g., complex
b = np.array([[1, 2],[3, 4]], dtype=complex)
print(b)
print(f"This is a complex array: {b.dtype}")
print("=" * 100)
# Note that numpy arrays can be multi-dimensional
# But it can't be inhomogeneous (e.g., mixing integers and strings, or mixing 1D and 2D arrays)
c = np.array([
    [[1, 2, 3], 
     [4, 5, 6]],
    [[7, 8, 9],
     [10, 11, 12]]
])
print(c) # layer, row, column
print(f"Dimension of the array: {c.shape}, total number of elements: {c.size}, number of axis: {c.ndim}")

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
This is a complex array: complex128
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimension of the array: (2, 2, 3), total number of elements: 12, number of axis: 3


In [18]:
# For method 3, using placeholders like zeros, ones, or empty
d = np.zeros((3, 4))
print(d)
print("=" * 100)
e = np.ones((2, 3, 4), dtype=np.int16)
print(e)
print("=" * 100)
# Empty array, the values are uninitialized (whatever was in memory at that time)
f = np.empty((2, 3))
print(f)
print(f"Type of the array: {f.dtype}")

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]
Type of the array: float64


In [21]:
# For method 4, using linspace to create an array with `evenly spaced` values over a specified interval
g = np.linspace(0, 1, 5) # Start at 0, end at 1, with 5 evenly spaced values
print(g)

[0.   0.25 0.5  0.75 1.  ]


### Basic Operation

In [29]:
a = np.arange(0, 9).reshape(3, 3)
print(a)
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3, 3)
print(b)
print("=" * 100)
# Common ones: +, -, *, /, //, %, **, etc.
# For matrix multiplication, use the @ operator or np.dot() function
print(f"Proof: a @ b = a.dot(b) = {a @ b}, {np.dot(a, b)}")

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Proof: a @ b = a.dot(b) = [[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]], [[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
