# NumPy Quickstart
For more detail please refer to https://numpy.org/doc/stable/user/quickstart.html

In [9]:
import numpy as np

# Creating a 2D array
a = np.arange(15).reshape(3, 5) # Rows: 3, Columns: 5, with range 0-14
print(a)

# Dimension of the array
print(f"Dimension of the array: {a.shape}, total number of elements: {a.size}, number of axis: {a.ndim}")

# Checking the type of the array
print(f"Type of the array: {a.dtype}")

# Itemsize of each element in bytes
print(f"Itemsize of each element: {a.itemsize} bytes")


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Dimension of the array: (3, 5), total number of elements: 15, number of axis: 2
Type of the array: int64
Itemsize of each element: 8 bytes


There are 3 ways for you to create an array: 1. np.arange(x).rehsape(y, z); 2. using np.array([add your own list of numbers here]); 3. using placeholders

In [ ]:
# For method 2, you could also specify the data type, e.g., complex
b = np.array([[1, 2],[3, 4]], dtype=complex)
print(b)

# 

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
